#index:
#    path: /
#    controller: App\Controller\DefaultController::index

# the "app_first" route name is not important yet
#app_lucky_number:
#    path: /first
#    controller: App\Controller\FirstController::number
